# Generated by Django 2.1.5 on 2019-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Expense Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payee', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpenseTypeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='expenses',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.PROTECT', to='expenses.ExpenseType'),
        ),
    ]
