# Generated by Django 2.1.5 on 2019-08-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='type',
            new_name='exp_type',
        ),
    ]
