# Generated by Django 2.1.5 on 2019-08-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20190829_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['date'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['ExpenseTypeName'], 'verbose_name_plural': 'Expense Types'},
        ),
        migrations.AddField(
            model_name='expenses',
            name='reimbursable',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Expense Amount'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exp_type',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.PROTECT', to='expenses.ExpenseType', verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payee',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payee'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='ExpenseTypeName',
            field=models.CharField(max_length=200, verbose_name='Expense Type'),
        ),
    ]
