# Generated by Django 2.1.5 on 2019-08-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20190830_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='reimbursable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
